### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by nPokemon** [MiChaelinzo/Trading-Agent-#1]
After training it , How do I perform the trade base on that trained models ? 
Thank.

**Comment by MiChaelinzo** [comment]
python3 eval.py data/GOOG_2019.csv --model-name model_GOOG_50 --debug

you can download random .csv files into https://www.kaggle.com/datasets/ 
for example, if you want Bitcoin https://www.kaggle.com/datasets/mczielinski/bitcoin-historical-data
download the data and run training and perform evaluation it will trade the historical data
